### ISSUE TITLE
Instructions for building the spec locally

### ISSUE THREAD

**Issue by OR13** [ietf-wg-mediaman/suffixes#10]
@msporny First time encountering this xml format, and guidance on previewing local changes?

**Comment by msporny** [comment]
> @msporny First time encountering this xml format, and guidance on previewing local changes?

Yes, here's how you do it:

1. Serve the directory from a web server on localhost.
2. Using a web browser, open the index.xml file.
3. It'll render to HTML using the magic of XSL (by reading the `rfc2629.xsl` file from the same directory and applying it to the XML file). Works in any Chromium browser and Firefox... not sure about Safari.

Closing since question has been answered.
