### ISSUE TITLE
Advice about processing structured syntaxes is problematic

### ISSUE THREAD

**Issue by TallTed** [ietf-wg-mediaman/suffixes#12]
The following is problematic advice:

https://github.com/ietf-wg-mediaman/suffixes/blob/da2c5b8fb00e5f4fa34606630043bc0db24dc301/index.xml#L166-L180

Processing a document of (non-existent) type `image/svg+xml+gzip` (by which I think you mean ["_an octet stream of type `image/svg+xml`, subsequently compressed with `gzip`_"](https://www.iana.org/assignments/media-types/image/svg+xml#:~:text=rfc1952%5D%2C%20i.e.-,octet%20streams%20of%20type%20image/svg%2Bxml%2C%20subsequently%20compressed%20with%20gzip,-.%0A%0AMacintosh%20file%20type)) with a `gzip` processor would get a document of whatever type the `gzip` processor emits — which may not be `image/svg+xml`! — which is encoded within the `gzip` document. A `gzip` processor does not look at nor care about the media type of the document it processes (though that document *should* be media type [`application/gzip`](https://www.iana.org/assignments/media-types/application/gzip)); the `gzip` processor takes in one byte-stream and emits another byte-stream, to which it assigns *whatever media type it finds encoded in the gzip document*.

Also note, there is no such media type as `image/xml`, so `image/svg+xml` [breaks existing RFC rules](https://www.rfc-editor.org/rfc/rfc2046.html#section-4.2)! `text/xml` and `application/xml` exist, but there is no path that takes a document from top-level type `image` to top-level type `text` nor top-level type `application`.

**Comment by msporny** [comment]
All of that guidance/processing has been removed to simplify the processing rules in the specification. We can no longer end up with non-existent media types. The processing rules are now entirely deterministic (though, less capable). I outlined the changes and requested a re-review from you here:

https://github.com/ietf-wg-mediaman/suffixes/issues/5#issuecomment-1629866802

where you seemed to indicate that you were ok w/ the updates to the specification (and suggested some changes):

https://github.com/ietf-wg-mediaman/suffixes/issues/5#issuecomment-1631445261

I believe this issue is addressed. I'm closing this issue, please feel free to re-open it if you disagree.
