### ISSUE TITLE
Consider: Deprecating usage of structured suffixes

### ISSUE THREAD

**Issue by msporny** [ietf-wg-mediaman/suffixes#24]
During [IETF 119](https://www.youtube.com/watch?v=xEGSm6oN7gw), @martinthomson noted that structured suffixes might have been a bad idea and the feature in media types should be deprecated.

One way the group could achieve this is by

1) updating the suffixes portion of the specification to note that the media type suffix feature is historical and is no longer to be used for future media types,
2) noting that the use of the `+` sign in media types is a historical convention that is no longer used,
3) deprecating the structured suffix registry, and all text related to it, and making it a historical document.

**Comment by martinthomson** [comment]
That isn't quite what I said, though I realize that this is subtle.

I suggested that perhaps - because we don't understand what it means to define a good suffix - that it might be worth recognizing that the semantics we attach to a suffix might have limited utility... or no utility at all.

That idea of zero utility seemed to catch on, but after looking into this a little more, it seems like we might still be able to recover something from the idea.  But it would be a far narrower concept than was previously conceived.

**Comment by OR13** [comment]
I think we are unlikely to halt the use of `+json` and `+cbor` based media type requests in IETF documents.

**Comment by EskoDijk** [comment]
I think a link should be added here to the IETF 119 meeting notes or other material to provide details.  For those who missed that WG meeting. In the present Github issue, the rationale for doing a deprecation is also not provided (maybe it's clearer in the meeting notes?)

As an example: isn't the utility of `+json` that a viewer of `foo+json` can automatically attempt to parse the data as `application/json` and then show the data in the same manner that `application/json` is shown -- e.g. with syntax highlighting, or as a tree model, or pretty-formatted, or with syntax check applied, etc. ?   (If this aspect was already discussed - sorry, ignore this, I don't want to redo the discussion necessarily.)

**Comment by msporny** [comment]
The WG seems to have settled on NOT deprecating usage of structured suffixes as of IETF 120 because there would be objections to this path forward and the WG didn't think it would be able to achieve consensus on such a proposal.
