### ISSUE TITLE
Registration template updates need to be specified

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/suffixes#6]
The registration template for suffixes probably needs revision.

**Comment by alvestrand** [comment]
Looking at the registry now, it seems clear that the rules about suffixes are routinely long enough that they shouldn't attempt to be a column in the table - a pointer to the defining document should be there instead.

**Comment by msporny** [comment]
I added 6bf7646c478ff93ca2e448bb27a6f3fe55814884 to get rid of the most egregious copy-paste pattern in the structured syntax registry. It looks like people are using the "... Considerations" columns in the registry to write spec text, when what they really should be doing is referring to a specification. Commit 6bf7646c478ff93ca2e448bb27a6f3fe55814884 is a step in the direction I think you want us to take @alvestrand (which I agree with).

If you are ok with that change, I can take it a bit further and try to add an "Updates to Registration" section that tells people to point to specifications instead of writing spec text in the SSS registry. However, before I do that, I wanted to make sure that you wanted to minimize the information in the "... Considerations" columns, or if you were just mostly concerned about the "Fragment Identifier Considerations" column?

Let me know what you want to do @alvestrand and I'll try to get a commit in that achieves it. I personally think that we're probably ok w/ just applying commit 6bf7646c478ff93ca2e448bb27a6f3fe55814884, but don't feel confident enough to close this issue on that basis.

**Comment by msporny** [comment]
@alvestrand ping again to see if the new text addresses your concern. I plan to close this issue by IETF 116 if I have not received a response by then.

**Comment by alvestrand** [comment]
No, I don't think it addresses my concern.

1) SHOULD is not the right thing here. Either they MUST be followed, or the SHOULD declaration needs to explain why and when the SHOULD is departed from. (The registry entry for +json is a particularly egregrious example of violating this rule. We should not make things worse by continuing the tradition.)

2) the term "resolve per the structured syntax registry" is undefined.

3) The term "full media type" is undefined.

3) This document is about the case of multiple suffixes. It isn't the place for generic suffix processing, it is the place for describing how suffixes traverse a sequence of decomposition.

For example - if you have image/svg+xml+gzip with the fragment ID #froosh, the +gzip suffix registration says that it should either resolve according to "application/gzip" (no suffix defined), in the spec for "+gzip" (either that's just the registration, or the reference is missing), or in the spec for "svg+xml+gzip" (does not exist). It does not allow looking for an image/svg+xml with the suffix #froosh to resolve the fragment ID.

If it did, the +xml registration seems to indicate that the registration for image/svg+xml should be in control.
That's the SVG spec, https://www.w3.org/TR/SVG/mimereg.html

I think this document needs to specify that when suffix removal is used to construct an "inner" media type, a relevant fragment identifier needs to follow the rules for the "inner" media type unless specifically overridden by processing rules for the "outer" media type.

The generic need to update the suffix registry format needs to go to the "procedures" bug list, I'll open a new one there.

(Apologies for not addressing this earlier - lost token).

**Comment by msporny** [comment]
> I think this document needs to specify that when suffix removal is used to construct an "inner" media type, a relevant fragment identifier needs to follow the rules for the "inner" media type unless specifically overridden by processing rules for the "outer" media type.

The latest -05 specification no longer attempts to define "how to construct an inner media type"... the latest draft abandons the "pipeline processing" approach and goes with something simpler ("just process the entire media type, the entire suffix, or a subset of the suffix, in order -- you can't mix and match, you don't construct an inner media type, no more pipelining options"... overall, a reduction in complexity. 

The latest spec has been been published here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html

The sections pertinent to your review comments are here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html#section-2

and here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html#section-2.1

Let me know if this addresses your concerns (as far as they can be addressed in this specification). The registration template being a mess is tracked elsewhere... don't know if we want to do anything about that in this spec. There is an attempt to be able to clean up the table by pointing the most egregious copy-paste into the suffixes table to normative specification text (as a link, instead of paragraphs of text in a column).

**Comment by msporny** [comment]
During IETF 117, it was decided that the registration template should be included in the specification. There was also discussion around changing the format of the registry due to the current state of the registry being difficult to read.

The next revision of the specification will include a structured suffix registration template.

**Comment by msporny** [comment]
> The next revision of the specification will include a structured suffix registration template.

The changes discussed during IETF 117 have been applied in this PR: f4c6e5c0bb14e8194e3730b0eb9c777cb6c3733a

To do this, I performed a verbatim copy of the corresponding section from RFC6838 and then made the following changes:

1. We no longer allow individuals to provide free-form text in the registration template. They have to point to a section in a specification that details encoding, interop, fragment processing, and security considerations.
2. We allow organizations to be change controllers now.
3. We say that the updated registration template will replace the one in RFC 6838 (eventually).

The most egregious copy-paste abuses of the registry are in the fragment processing entry (which we can now point to the new Fragment Processing section in this document, as it's the same text) and the security considerations (which we can point to the security considerations in the spec that defines the structured suffix).

I believe this might address your concerns, @alvestrand? If not, please let me know what else needs to be changed.

**Comment by msporny** [comment]
IETF 118 outcome: change seems to be fine. Closing.
